<?php
/**
 * The Case Study project gallery.
 *
 * One component for both divisions, the same reasoning as the About page parts:
 * the markup lives here once and each division styles it through the body class
 * its own stylesheet already keys off.
 *
 * @package Nice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Return the approved gallery attachment ids for a Case Study.
 *
 * Gated on the same approval tick as the hero image. An unapproved record
 * returns nothing at all rather than a placeholder per image: a row of empty
 * frames says less than no row.
 *
 * @param int $post_id Case Study ID.
 * @return int[]
 */
function nice_theme_get_case_study_gallery( $post_id ) {
	if ( ! function_exists( 'nice_theme_media_approved' ) || ! nice_theme_media_approved( $post_id ) ) {
		return array();
	}

	$ids = get_post_meta( $post_id, '_nice_gallery_ids', true );

	if ( function_exists( 'nice_sanitize_gallery_ids' ) ) {
		return nice_sanitize_gallery_ids( $ids );
	}

	return is_array( $ids ) ? array_map( 'absint', $ids ) : array();
}

/**
 * Render the project gallery for a Case Study.
 *
 * @param int    $post_id  Case Study ID.
 * @param string $division Division slug, for the styling hook.
 */
function nice_render_case_study_gallery( $post_id, $division = '' ) {
	$ids = nice_theme_get_case_study_gallery( $post_id );

	if ( ! $ids ) {
		return;
	}

	$division = sanitize_key( $division );
	$modifier = $division ? ' nice-project-gallery--' . $division : '';
	?>
	<section class="nice-project-gallery<?php echo esc_attr( $modifier ); ?>" aria-labelledby="nice-project-gallery-title">
		<div class="nice-wide">
			<h2 id="nice-project-gallery-title" class="nice-sr-only"><?php esc_html_e( 'Project gallery', 'nice' ); ?></h2>
			<ul class="nice-project-gallery__list">
				<?php
				foreach ( $ids as $id ) :
					$alt = (string) get_post_meta( $id, '_wp_attachment_image_alt', true );

					/*
					 * Every one of these is lazy. The gallery sits below the project
					 * write-up, so none of it is near the fold, and an eager image
					 * here would compete with the hero above for the first paint --
					 * which is the one picture a reader is actually waiting on.
					 */
					$attributes = array(
						'alt'      => $alt,
						'loading'  => 'lazy',
						'decoding' => 'async',
						'sizes'    => '(min-width: 64rem) 50vw, 100vw',
					);
					?>
					<li class="nice-project-gallery__item">
						<?php echo wp_get_attachment_image( $id, 'large', false, $attributes ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by wp_get_attachment_image(). ?>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>
	</section>
	<?php
}
