<?php
/**
 * Server-rendered Studio Home presentation.
 *
 * @package Nice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Render one responsive Studio featured image.
 *
 * @param WP_Post             $post       CMS record.
 * @param string              $sizes      Responsive sizes value.
 * @param array<string,mixed> $attributes Additional image attributes.
 * @return string
 */
function nice_get_studio_featured_image( $post, $sizes, $attributes = array() ) {
	if ( ! $post instanceof WP_Post || ! function_exists( 'nice_theme_get_featured_image' ) ) {
		return '';
	}

	return nice_theme_get_featured_image( $post->ID, $sizes, $attributes );
}

/**
 * Return only approved, currently available contact actions.
 *
 * @return array<int,array{channel:string,label:string,url:string}>
 */
function nice_get_studio_contact_actions() {
	$labels  = array( 'whatsapp' => 'WhatsApp', 'email' => 'Email', 'phone' => 'Phone' );
	$actions = array();

	foreach ( $labels as $channel => $label ) {
		$action = nice_get_contact_action( $channel, '#studio-contact-pending' );

		if ( ! $action['placeholder'] ) {
			$actions[] = array( 'channel' => $channel, 'label' => $label, 'url' => $action['url'] );
		}
	}

	return $actions;
}

/**
 * Render the Studio Home block.
 *
 * @return string
 */
function nice_render_studio_home() {
	$services     = nice_get_studio_home_services();
	$case_studies = nice_get_studio_home_case_studies();
	$clients      = nice_get_studio_home_clients();
	$hero_source  = nice_get_studio_hero_source( $services );
	$hero_image   = nice_get_studio_featured_image(
		$hero_source,
		'100vw',
		array(
			'alt'           => '',
			'loading'       => 'eager',
			'decoding'      => 'async',
			'fetchpriority' => 'high',
		)
	);
	$social_links = function_exists( 'nice_get_social_links' ) ? nice_get_social_links() : array();
	$actions      = nice_get_studio_contact_actions();
	$home_url     = esc_url( home_url( '/' ) );

	ob_start();
	?>
	<div class="nice-studio-subnav-shell">
		<nav class="nice-wide nice-studio-subnav" aria-label="Studio navigation">
			<a href="#studio-top" aria-current="page">Studio Home</a>
			<a href="#studio-services">Services</a>
			<a href="#studio-work">Selected Work</a>
			<a href="#studio-clients">Clients</a>
			<a href="#studio-contact">Contact</a>
		</nav>
	</div>

	<section class="nice-studio-hero" id="studio-top" aria-labelledby="nice-studio-title">
		<?php if ( $hero_image ) : ?>
			<div class="nice-studio-hero__media" aria-hidden="true"><?php echo $hero_image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by wp_get_attachment_image(). ?></div>
		<?php else : ?>
			<picture class="nice-studio-hero__media" aria-hidden="true">
				<source media="(max-width: 47.99rem)" srcset="<?php echo esc_url( get_theme_file_uri( '/assets/images/strata-production-480.webp' ) ); ?>">
				<img src="<?php echo esc_url( get_theme_file_uri( '/assets/images/strata-production.webp' ) ); ?>" width="545" height="305" alt="" decoding="async" fetchpriority="high">
			</picture>
		<?php endif; ?>
		<div class="nice-studio-hero__veil" aria-hidden="true"></div>
		<div class="nice-wide nice-studio-hero__inner">
			<div class="nice-studio-hero__identity" data-nice-reveal>
				<p class="nice-eyebrow">NICE / Studio</p>
				<h1 id="nice-studio-title" class="nice-editorial">Studio</h1>
			</div>
			<div class="nice-studio-hero__statement" data-nice-reveal>
				<p class="nice-editorial" data-nice-editorial-reveal>Stories shaped<br>for every screen.</p>
				<span>Film, television and digital storytelling brought together through creative production, design and content strategy.</span>
			</div>
		</div>
	</section>

	<section class="nice-studio-services nice-studio-section" id="studio-services" aria-labelledby="nice-studio-services-title">
		<div class="nice-wide">
			<header class="nice-studio-heading" data-nice-reveal>
				<p class="nice-eyebrow">Studio services</p>
				<h2 id="nice-studio-services-title">Built to move from idea to image.</h2>
			</header>
			<?php if ( $services ) : ?>
				<div class="nice-studio-services__grid">
					<?php foreach ( $services as $index => $service ) :
						$image = nice_get_studio_featured_image( $service, '(min-width: 75rem) 760px, (min-width: 48rem) 58vw, calc(100vw - 40px)' );
					?>
						<article class="nice-studio-service nice-studio-service--<?php echo esc_attr( $index + 1 ); ?>" data-nice-studio-service="<?php echo esc_attr( $service->post_name ); ?>" data-nice-reveal>
							<?php if ( $image ) : ?><div class="nice-studio-service__media"><?php echo $image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by wp_get_attachment_image(). ?></div><?php endif; ?>
							<div class="nice-studio-service__body">
								<span class="nice-studio-index"><?php echo esc_html( sprintf( '%02d', $index + 1 ) ); ?></span>
								<h3><?php echo esc_html( $service->post_title ); ?></h3>
								<p><?php echo esc_html( $service->post_excerpt ?: wp_trim_words( wp_strip_all_tags( $service->post_content ), 28 ) ); ?></p>
								<span class="nice-studio-future-link" aria-disabled="true" data-nice-future-path="<?php echo esc_attr( '/studio/services/' . $service->post_name . '/' ); ?>">Detailed service page follows</span>
							</div>
						</article>
					<?php endforeach; ?>
				</div>
			<?php else : ?>
				<div class="nice-studio-pending" data-nice-studio-services-pending>
					<p class="nice-eyebrow">Publication pending</p>
					<h3>Studio service details are being prepared.</h3>
				</div>
			<?php endif; ?>
		</div>
	</section>

	<section class="nice-studio-capabilities" aria-labelledby="nice-studio-capabilities-title">
		<div class="nice-wide nice-studio-capabilities__inner">
			<header data-nice-reveal>
				<p class="nice-eyebrow">What Studio does</p>
				<h2 id="nice-studio-capabilities-title">Creative production across formats.</h2>
				<p>Visual work shaped for screens, channels and the people watching.</p>
			</header>
			<ul data-nice-reveal>
				<li><span>01</span>Film Productions</li>
				<li><span>02</span>Corporate AVs</li>
				<li><span>03</span>Product Photo-shoots</li>
				<li><span>04</span>Training Visual Aid / Whiteboard Animations</li>
				<li><span>05</span>Digital Storytelling</li>
			</ul>
		</div>
	</section>

	<section class="nice-studio-work nice-studio-section" id="studio-work" aria-labelledby="nice-studio-work-title">
		<div class="nice-wide">
			<header class="nice-studio-heading" data-nice-reveal>
				<p class="nice-eyebrow">Selected Studio work</p>
				<h2 id="nice-studio-work-title">Production with a point of view.</h2>
			</header>
			<?php if ( $case_studies ) : ?>
				<div class="nice-studio-work__grid">
					<?php foreach ( $case_studies as $index => $case_study ) :
						$image        = nice_get_studio_featured_image( $case_study, '(min-width: 75rem) 760px, (min-width: 48rem) 55vw, calc(100vw - 40px)' );
						$client       = function_exists( 'nice_get_case_study_client_name' ) ? nice_get_case_study_client_name( $case_study->ID ) : '';
						$service_name = nice_get_studio_case_study_service_name( $case_study->ID );
					?>
						<article class="nice-studio-project nice-studio-project--<?php echo esc_attr( $index + 1 ); ?>" data-nice-studio-project="<?php echo esc_attr( $case_study->post_name ); ?>" data-nice-reveal>
							<?php if ( $image ) : ?><div class="nice-studio-project__media"><?php echo $image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by wp_get_attachment_image(). ?></div><?php endif; ?>
							<div class="nice-studio-project__meta">
								<?php if ( $service_name ) : ?><span><?php echo esc_html( $service_name ); ?></span><?php endif; ?>
								<?php if ( $client ) : ?><span><?php echo esc_html( $client ); ?></span><?php endif; ?>
							</div>
							<h3><?php echo esc_html( $case_study->post_title ); ?></h3>
							<p><?php echo esc_html( $case_study->post_excerpt ?: wp_trim_words( wp_strip_all_tags( $case_study->post_content ), 30 ) ); ?></p>
						</article>
					<?php endforeach; ?>
				</div>
			<?php else : ?>
				<div class="nice-studio-pending" data-nice-studio-work-pending>
					<p class="nice-eyebrow">Publication pending</p>
					<h3>Selected Studio work is being prepared.</h3>
				</div>
			<?php endif; ?>
		</div>
	</section>

	<section class="nice-studio-story" aria-labelledby="nice-studio-story-title">
		<div class="nice-wide nice-studio-story__inner">
			<header data-nice-reveal>
				<p class="nice-eyebrow">The Studio perspective</p>
				<h2 id="nice-studio-story-title">From conception to screen.</h2>
			</header>
			<ol data-nice-reveal>
				<li><span>01</span><strong>Story</strong></li>
				<li><span>02</span><strong>Production</strong></li>
				<li><span>03</span><strong>Screen</strong></li>
			</ol>
			<p data-nice-reveal>NICE brings creative production, design, content strategy and marketing together to shape narratives across film, television, digital channels, stages and social platforms.</p>
		</div>
	</section>

	<section class="nice-studio-clients nice-studio-section" id="studio-clients" aria-labelledby="nice-studio-clients-title">
		<div class="nice-wide">
			<header class="nice-studio-heading" data-nice-reveal>
				<p class="nice-eyebrow">Shared collaborations</p>
				<h2 id="nice-studio-clients-title">One NICE client community.</h2>
			</header>
			<?php if ( $clients ) : ?>
				<ul class="nice-studio-clients__list" data-nice-reveal>
					<?php foreach ( $clients as $client ) :
						$client_url = esc_url( get_post_meta( $client->ID, '_nice_client_url', true ) );
					?>
						<li><?php if ( $client_url ) : ?><a href="<?php echo $client_url; ?>"><?php echo esc_html( $client->post_title ); ?></a><?php else : ?><?php echo esc_html( $client->post_title ); ?><?php endif; ?></li>
					<?php endforeach; ?>
				</ul>
			<?php else : ?>
				<div class="nice-studio-pending" data-nice-studio-clients-pending><p>Approved client details are being prepared.</p></div>
			<?php endif; ?>
		</div>
	</section>

	<?php if ( $social_links ) : ?>
		<section class="nice-studio-social" aria-labelledby="nice-studio-social-title">
			<div class="nice-wide nice-studio-social__inner">
				<h2 id="nice-studio-social-title">Follow NICE Studio.</h2>
				<nav aria-label="NICE social channels">
					<?php foreach ( $social_links as $index => $social_url ) :
						$host = preg_replace( '/^www\./', '', (string) wp_parse_url( $social_url, PHP_URL_HOST ) );
					?>
						<a href="<?php echo esc_url( $social_url ); ?>" rel="noopener noreferrer"><?php echo esc_html( $host ?: sprintf( 'Social channel %d', $index + 1 ) ); ?></a>
					<?php endforeach; ?>
				</nav>
			</div>
		</section>
	<?php endif; ?>

	<section class="nice-studio-contact" id="studio-contact" aria-labelledby="nice-studio-contact-title">
		<div class="nice-wide nice-studio-contact__inner">
			<div data-nice-reveal>
				<p class="nice-eyebrow">Start a conversation</p>
				<h2 id="nice-studio-contact-title" class="nice-editorial" data-nice-editorial-reveal>Have a story to tell?<br>Bring it to the screen.</h2>
			</div>
			<?php if ( $actions ) : ?>
				<div class="nice-studio-contact__actions" aria-label="Approved contact options" data-nice-reveal>
					<?php foreach ( $actions as $action ) : ?>
						<a class="nice-button nice-button--primary" href="<?php echo esc_url( $action['url'] ); ?>" data-nice-contact-channel="<?php echo esc_attr( $action['channel'] ); ?>"><?php echo esc_html( $action['label'] ); ?></a>
					<?php endforeach; ?>
				</div>
			<?php else : ?>
				<div class="nice-studio-contact__pending" id="studio-contact-pending" data-nice-studio-contact-pending data-nice-reveal>
					<p class="nice-eyebrow">Publication pending</p>
					<p>Approved contact channels will appear here when they are ready.</p>
				</div>
			<?php endif; ?>
		</div>
	</section>

	<a class="nice-studio-return" href="<?php echo $home_url; ?>">Back to NICE <span aria-hidden="true">-&gt;</span></a>
	<?php
	return (string) ob_get_clean();
}

/**
 * Register the request-time Studio Home block.
 */
function nice_register_studio_home_block() {
	register_block_type(
		'nice/studio-home',
		array(
			'render_callback' => 'nice_render_studio_home',
		)
	);
}
add_action( 'init', 'nice_register_studio_home_block' );
